### ISSUE TITLE
您好！作者，这个可以给linux_arm386的编绎方法吗？

### ISSUE THREAD

**Issue by sunup2015** [dev-lluo/frps-auth#10]
您好！作者，这个可以给linux_arm386的编绎方法吗？
Hello! Author, can this be compiled for linux_arm386?

**Comment by dev-lluo** [comment]
`CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build`
GOOS：目标平台的操作系统（darwin、freebsd、linux、windows）
GOARCH：目标平台的体系架构（386、amd64、arm）
