### ISSUE TITLE
0.dat这个数据库文件原来只有8M，现在变成256M了

### ISSUE THREAD

**Issue by sunup2015** [dev-lluo/frps-auth#11]
作者，您好，0.dat这个数据库文件原来只有8M，现在变成256M了，这个有办法还是变回以前8M这个大小的吗？

**Comment by sunup2015** [comment]
> 该文件是[nutsdb](https://github.com/xujiajun/nutsdb)数据库的文件；该数据库中存储的是你在界面上定义的规则；能提供一下你定义的规则大概数量
现在是初始状态还没建规则就是这256M了

**Comment by dev-lluo** [comment]
https://github.com/nutsdb/nutsdb

> > 该文件是[nutsdb](https://github.com/xujiajun/nutsdb)数据库的文件；该数据库中存储的是你在界面上定义的规则；能提供一下你定义的规则大概数量
> 
> 现在是初始状态还没建规则就是这256M了

请查看该数据库的readme

` Note: Starting from v0.9.0, defaultSegmentSize in DefaultOptions has been adjusted from 8MB to 256MB. `

**Comment by sunup2015** [comment]
> 

好的，感谢感谢！
