### ISSUE TITLE
stcp的页面选项中多了个空格, 会造成验证失败

### ISSUE THREAD

**Issue by yyjdelete** [dev-lluo/frps-auth#13]
https://github.com/dev-lluo/frps-auth/blob/2c15ab4c23972ac07c6d0db2fae395878ac3c0cd/static/form.html#L33

**Comment by sunup2015** [comment]
> https://github.com/dev-lluo/frps-auth/blob/2c15ab4c23972ac07c6d0db2fae395878ac3c0cd/static/form.html#L33

这个最新版已经早都修复了的

**Comment by yyjdelete** [comment]
@sunup2015 
上面链接的代码就是最新的, 2020年之后应该就没改过

测试了下[v0.4.20.beta](https://github.com/dev-lluo/frps-auth/releases/tag/v0.4.20.beta)也没修啊

本地试了下浏览器F12替换之后新添加的stcp是能过验证的, 改之前保存的配置不了验证

**Comment by sunup2015** [comment]
> @sunup2015 上面链接的代码就是最新的, 2020年之后应该就没改过
> 
> 测试了下[v0.4.20.beta](https://github.com/dev-lluo/frps-auth/releases/tag/v0.4.20.beta)也没修啊
> 
> 本地试了下浏览器F12替换之后新添加的stcp是能过验证的, 改之前保存的配置不了验证

![image](https://user-images.githubusercontent.com/30277413/197385882-fee99d16-0cb5-408d-a027-f7d3a223f4ea.png)

**Comment by yyjdelete** [comment]
@sunup2015
恩, 就是这个空格, 会造成后续js验证和鉴权验证全部失败
![image](https://user-images.githubusercontent.com/1819074/197386045-7fb3c2c8-6e2f-4ed4-a52a-f64dabef1cb3.png)

![image](https://user-images.githubusercontent.com/1819074/197386029-61c5f895-0793-436d-97f4-5aa570bda7e6.png)

**Comment by sunup2015** [comment]
可以重新clone了编绎一下

**Comment by chi-cat** [comment]
修复
