### ISSUE TITLE
stcp和xtcp都无需指定(remote_port) 但在 “提示配置信息”里出现&建议

### ISSUE THREAD

**Issue by xqzr** [dev-lluo/frps-auth#3]
![image](https://user-images.githubusercontent.com/34030394/78808180-a88e4300-79f7-11ea-8886-9a0393b2954b.png)
![image](https://user-images.githubusercontent.com/34030394/78808205-b0e67e00-79f7-11ea-9789-0a1af4f570b1.png)
![image](https://user-images.githubusercontent.com/34030394/78808294-cbb8f280-79f7-11ea-88a7-c78c929b7afe.png)
建议把这里改成“HTTP/HTTPS”或者把这两个协议独立开 来配置↑

**Comment by dev-lluo** [comment]
关于xtcp和stcp的问题会在稍后修正，至于http和https分拆还在考虑中，
1.目前frp支持tls，所以在使用本地http服务时，其实也可以使得frpc到frps的数据加密，然后再frps端统一使用https，比如nginx/apache代理，达到全程加密
2.本地启用https时显得麻烦，证书配置或者使用frps的http2https的插件

**Comment by xqzr** [comment]
> 关于xtcp和stcp的问题会在稍后修正，至于http和https分拆还在考虑中，
> 1.目前frp支持tls，所以在使用本地http服务时，其实也可以使得frpc到frps的数据加密，然后再frps端统一使用https，比如nginx/apache代理，达到全程加密
> 2.本地启用https时显得麻烦，证书配置或者使用frps的http2https的插件

不是所有的frpc都使用“subdomain”
如果在frps端部署nginx的话 使用“custom_domains”的frpc就会证书错误

**Comment by xqzr** [comment]
> 关于xtcp和stcp的问题会在稍后修正，至于http和https分拆还在考虑中，
> 1.目前frp支持tls，所以在使用本地http服务时，其实也可以使得frpc到frps的数据加密，然后再frps端统一使用https，比如nginx/apache代理，达到全程加密
> 2.本地启用https时显得麻烦，证书配置或者使用frps的http2https的插件

第一条 我希望遵循frp

**Comment by xqzr** [comment]
几天了，鸽了？

**Comment by dev-lluo** [comment]
公司最近比较忙

发自我的iPhone

在 2020年4月13日，12:08，xqzr <notifications@github.com> 写道：

﻿

几天了，鸽了？

**Comment by xqzr** [comment]
可以先把“stcp和xtcp”问题解决 web拖一下。。

**Comment by dev-lluo** [comment]
我没有stcp和xtcp的真实使用场景；是否需要对sk进行锁定

**Comment by xqzr** [comment]
不用 有meta_auth认证就好

**Comment by xqzr** [comment]
还不能发布新版本吗？
