### ISSUE TITLE
关于修改4000平台后台禁用某个渠道不重启frpc无效

### ISSUE THREAD

**Issue by bianyingshan** [dev-lluo/frps-auth#4]
经过多次测试，情况如下：
1、如果后台4000正常添加渠道配置，然后启动客户端会报：start proxy success，这个没问题。
2、如果后台4000正常添加渠道配置，禁用掉，然后启动客户端会报：start error: invalid[disabled]，这个没问题。
3、如果后台被禁用了，然后启动，不重启frpc，30s后会自动变为：start proxy success，但是反过来不会。异常情况就在这里。比如说：目前frpc已经是start proxy success，但是我在4000平台禁用掉，**frpc无论过多长时间，管道依然生效，没被禁用掉，还是必须重启frpc？这个反过来就不行，感觉很奇怪**

**Comment by dev-lluo** [comment]
请留意readme中第5点的注意事项；由于目前plugin的插拔点不支持心跳报告；所以我在就的master上进行了分支加上了插拔点；但是在dev分支上作者已经加入类似插拔点，所以目前在dev上的插拔点未合并之前只有我的分支上编译的版本支持即时禁用生效；详情参见以下。
```
注意；开启禁用后；在frp默认版本上只有在客户端重启或网络链接断开后重新连接时生效; 如果需要即时生效；请访问(ping-plugin分支)[https://github.com/dev-lluo/frp/tree/ping-plugin] ;此分支为个人修改版本。 根据和frp作者大大沟通；在frp的dev分支上已经加入了类似的api，此功能可能会在dev合并到master分支后发生更改。
```

**Comment by MasamiYui** [comment]
> 请留意readme中第5点的注意事项；由于目前plugin的插拔点不支持心跳报告；所以我在就的master上进行了分支加上了插拔点；但是在dev分支上作者已经加入类似插拔点，所以目前在dev上的插拔点未合并之前只有我的分支上编译的版本支持即时禁用生效；详情参见以下。
> 
> ```
> 注意；开启禁用后；在frp默认版本上只有在客户端重启或网络链接断开后重新连接时生效; 如果需要即时生效；请访问(ping-plugin分支)[https://github.com/dev-lluo/frp/tree/ping-plugin] ;此分支为个人修改版本。 根据和frp作者大大沟通；在frp的dev分支上已经加入了类似的api，此功能可能会在dev合并到master分支后发生更改。
> ```

您好，我尝试clone ping-plugin分支，并重新编译，但是似乎FRPS授权并未实时生效，我的配置信息如下：
frps.ini:
```
[common]
bind_port = 7000
vhost_https_port = 443
vhost_http_port = 80
subdomain_host = xxx.cn
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin

[plugin.port-manager]
addr=0.0.0.0:4000
path=/auth
ops=NewProxy
```

frpc.ini:
```
[common]
server_addr = 10.44.239.60
server_port = 7000

[http-xxx2]
type=https
local_port = 443
subdomain=soc2
meta_auth_valid_to=1596153600000
meta_auth_key=8106eae1-6950-4fb5-8355-b6a16cf3fc33

```
frps-auth.ini:
```
address=0.0.0.0
#frps-auth的运行端口
port=4000
#后台管理用户名
username=cybersky
#后台管理密码;此项必填
password=cybersky
#签名盐值；此项必填；一个随机字符串
salt=cybersky123!@
```
请问我还需要配置什么吗？我尝试在服务器和客户端中都加入，同样没有看到及时生效的效果，我该怎么配置呢？
`authenticate_heartbeats = true
`

**Comment by dev-lluo** [comment]
设置ops=NewProxy,Heartbeat

发自我的iPhone

在 2020年7月21日，16:38，MasamiYui <notifications@github.com> 写道：

﻿

请留意readme中第5点的注意事项；由于目前plugin的插拔点不支持心跳报告；所以我在就的master上进行了分支加上了插拔点；但是在dev分支上作者已经加入类似插拔点，所以目前在dev上的插拔点未合并之前只有我的分支上编译的版本支持即时禁用生效；详情参见以下。

注意；开启禁用后；在frp默认版本上只有在客户端重启或网络链接断开后重新连接时生效; 如果需要即时生效；请访问(ping-plugin分支)[https://github.com/dev-lluo/frp/tree/ping-plugin] ;此分支为个人修改版本。 根据和frp作者大大沟通；在frp的dev分支上已经加入了类似的api，此功能可能会在dev合并到master分支后发生更改。


您好，我尝试clone ping-plugin分支，并重新编译，但是似乎FRPS授权并未实时生效，我的配置信息如下：
frps.ini:

[common]
bind_port = 7000
vhost_https_port = 443
vhost_http_port = 80
subdomain_host = xxx.cn
dashboard_port = 7500
dashboard_user = admin
dashboard_pwd = admin

[plugin.port-manager]
addr=0.0.0.0:4000
path=/auth
ops=NewProxy


frpc.ini:

[common]
server_addr = 10.44.239.60
server_port = 7000

[http-xxx2]
type=https
local_port = 443
subdomain=soc2
meta_auth_valid_to=1596153600000
meta_auth_key=8106eae1-6950-4fb5-8355-b6a16cf3fc33



frps-auth.ini:

address=0.0.0.0
#frps-auth的运行端口
port=4000
#后台管理用户名
username=cybersky
#后台管理密码;此项必填
password=cybersky
#签名盐值；此项必填；一个随机字符串
salt=cybersky123!@


请问我还需要配置什么吗？我尝试在服务器和客户端中都加入，同样没有看到及时生效的效果，我该怎么配置呢？
authenticate_heartbeats = true
